apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: organizationservice
  name: organizationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: organizationservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: organizationservice
    spec:
      containers:
        - env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8071
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: 072085842419.dkr.ecr.eu-west-1.amazonaws.com/ostock/organization-service:latest
          name: organizationservice
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
