spring:
  application:
    name: organization-service
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true

logging:
  level:
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
